/** Prints an API response. Used to return the API response to the client.
 * @param {Object} res Express result. Usually the first parameter in an express middleware function
 * @param {Object} apiResponse An API response generated by the API util. Expects a specific format
 */
const printResponse = (res, apiResponse) => {
  res.status(apiResponse.statusCode).json(apiResponse);
};

//* EXPORTS
module.exports = printResponse;
